README.md
Same as: https://github.com/ArkEcosystem/python-client/pull/9
=> Add "Guide for contributing" section to the readme

.gitignore, Makefile, crypto/exceptions.py, crypto/serializer.py, crypto/serializers/base.py, crypto/serializers/delegate_registration.py, crypto/serializers/delegate_resignation.py, crypto/serializers/ipfs.py, crypto/serializers/multi_payment.py, crypto/serializers/multi_signature_registration.py, crypto/serializers/second_signature_registration.py, crypto/serializers/timelock_transfer.py, crypto/serializers/transfer.py, crypto/serializers/vote.py, setup.cfg, setup.py, tests/conftest.py, tests/serializers/test_delegate_registration.py, tests/serializers/test_delegate_resignation.py, tests/serializers/test_ipfs.py, tests/serializers/test_multi_payment.py, tests/serializers/test_multi_signature_registration.py, tests/serializers/test_second_signature_registration.py, tests/serializers/test_timelock_transfer.py, tests/serializers/test_transfer.py, tests/serializers/test_vote.py, tests/test_dummy.py
Added all serializers and wrote tests for them. Some serializers don't work yet even though the code for them is written because I need to implement other modules (eg. `Network`) to make them work.
=> add serializers + transaction type fixtures + tests

crypto/constants.py, crypto/exceptions.py, crypto/identity/keys.py, crypto/message.py, crypto/serializer.py, setup.py, tests/identity/test_keys.py, tests/test_message.py
**Changes:**
- Added functionalities for signing/verifying a message and generating private/public key.
- Added constants for transaction types and fees.
=> sign/verify msg + methods for getting private/public keys

README.md
This is the final to-do list for features that need to be implemented in a crypto package.
Also check https://docs.ark.io/docs/cryptography-guidelines to make sure you are following the final guidelines.
=> chore: add to-do to readme

README.md
Adds a link to the official documentation as all other repositories have.
What types of changes does your code introduce?
=> chore: add docs link & codecov badge to readme

.coveragerc, .travis.yml, setup.py
Added code coverage.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
None
=> Add codecov

config.ini, crypto/conf.py, crypto/identity/address.py, crypto/identity/keys.py, crypto/identity/wif.py, crypto/message.py, crypto/resources/transaction.py, crypto/transactions/builder/base.py, crypto/transactions/builder/second_signature_registration.py, crypto/transactions/builder/transfer.py, crypto/transactions/deserializers/delegate_registration.py, crypto/transactions/deserializers/second_signature_registration.py, crypto/transactions/deserializers/transfer.py, setup.py, tests/identity/test_address.py, tests/identity/test_wif.py, tests/test_message.py, tests/transactions/builder/test_delegate_registration.py, tests/transactions/builder/test_multi_signature_registration.py, tests/transactions/builder/test_second_signature_registration.py, tests/transactions/builder/test_transfer.py, tests/transactions/builder/test_vote.py, tests/transactions/deserializers/test_delegate_registration.py, tests/transactions/deserializers/test_second_signature_registration.py
This change fixes transaction signing which is currently broken. I was able to successfully create and send one, see [here](https://dexplorer.ark.io/transaction/6c05c5da0ce8b112ca3b52c9989cf9fad0467329e0e810cf8b151ae133489eb0).
Another change that I made is that you shouldn't have to encode strings every time.
How to create a transaction:
```
from crypto.serializer import Serializer
from crypto.conf import use_network
from crypto.transactions.builder.transfer import TransferBuilder
use_network('devnet')
tx = TransferBuilder(recipientId='D5rHMAmTXVbG7HVF3NvTN3ghpWGEii5mH2', amount=1000, vendorField='broadcast me pleaaase!')
tx.sign('im a little passphrase yo')
```
To get the json object of a transaction do:
```
tx.to_json()
```
Use that JSON object then when sending a transaction.
What …
=> Fix transaction signing + solve issues #24 + remove nethash

crypto/identity/address.py
Remove the hardcoded address from the validate_address function. Don't judge. 🙅‍♂️ 
Also, don't count this PR towards a bounty, I don't deserve it.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
None
=> Fix validate_address function

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Fix wrong contribution link
What types of changes does your code introduce?
=> fix: wrong contributing link

README.md
Updated the README.md to reflect the latest changes
=> docs: update todos in readme.md

README.md
This pull request applies the badge style outlined in https://github.com/ArkEcosystem/boilerplate and fixes the `All Contributors` link.
=> chore: fixes badges / contributors link in readme

.circleci/config.yml, .coveragerc
Adds Codecov to CircleCI config.
=> chore: add codecov to circleci config

.circleci/config.yml
Properly stores test-results in CircleCI.
=> chore: store test results

README.md, setup.py
Changes `ARK` to `Ark` where appropriate.
=> chore: adhere to naming convention

crypto/transactions/transaction.py
=> fix: 64 length vendorfield not 63

crypto/transactions/builder/transfer.py
check if amount is int or float.
=> fix: check amout

crypto/transactions/transaction.py
=> feat: support new vendorfield length

.github/workflows/test.yml
=> ci: setup github action workflow for testing

crypto/transactions/builder/multi_payment.py
Adds the vendorField argument to the MultiPayment builder.
=> fix: enable vendorfield for multipayment

.github/workflows/test.yml
Updated GitHub CI to test against newer versions of Python.
The code is compatible with the latest version of Python (3.9 at the time of this writing) so it should be tested against this version.
- [] Documentation _(if necessary)_
=> ci: test against python 3.8 and 3.9

tests/configuration/test_network.py, tests/transactions/builder/test_delegate_registration.py, tests/transactions/builder/test_delegate_resignation.py, tests/transactions/builder/test_htlc_claim.py, tests/transactions/builder/test_htlc_lock.py, tests/transactions/builder/test_htlc_refund.py, tests/transactions/builder/test_ipfs.py, tests/transactions/builder/test_multi_payment.py, tests/transactions/builder/test_second_signature_registration.py, tests/transactions/builder/test_transfer.py, tests/transactions/builder/test_vote.py
Added additional unit tests to increase test coverage for builder/transactions tests.
=> chore: Increase test coverage for transactions

.github/workflows/test.yml, README.md
=> chore: update README links 
